version = 3.9.8
runner.dialect = scala3

align.preset = none
align {
  tokens = [
    {
      code = "=>"
      owners = [{
        regex = "Case"
      }]
    },
    {
      code = "%"
      owners = [{
        regex = "Term.ApplyInfix"
      }]
    }, {
      code = "%%"
      owners = [{
        regex = "Term.ApplyInfix"
      }]
    }
  ]
  closeParenSite = false
  openParenCallSite = false
  openParenDefnSite = false
}

danglingParentheses {
  callSite = true
  defnSite = true
}

docstrings {
  oneline = fold
  removeEmpty = true
  style = AsteriskSpace
  wrap = fold
}

indent.main = 2
indent {
  callSite = 2
  caseSite = 5
  defnSite = 4
}

lineEndings = unix

maxColumn = 80

newlines {
  afterCurlyLambdaParams = squash
  avoidInResultType = true
  beforeMultiline = fold
  implicitParamListModifierForce = [after]
  topLevelStatementBlankLines = [
    { maxNest = 0, blanks = 2 }
  ]
}

rewrite.rules = [
  Imports,
  PreferCurlyFors,
  RedundantBraces,
  RedundantParens,
  SortModifiers,
]

rewrite.imports.expand = true

rewrite {
  redundantBraces {
    ifElseExpressions = false
    stringInterpolation = true
  }

  sortModifiers.preset = styleGuide

  trailingCommas {
    style = always
    allowFolding = true
  }

  scala3 {
    convertToNewSyntax = true
    removeOptionalBraces.enabled = true
  }
}

verticalMultiline.newlineAfterOpenParen = true
